### ISSUE TITLE
Literally does not work at all when downloaded 

### ISSUE THREAD

**Issue by Th3SnowyOwl** [28klotlucas2/Funkin-Html5#1]
its just stuck on the loading screen, any ideas?

**Comment by 28klotlucas2** [comment]
First, make sure all files are downloaded. Secondly, put all of the files directly on your man drive not in a folder.
Lmk if it doesn't work.

**Comment by 28klotlucas2** [comment]
Nvm, It just won't work when downloaded.
I'll find a fix soon.

**Comment by 28klotlucas2** [comment]
I will convert it to a standalone desktop version.

**Comment by 28klotlucas2** [comment]
But to be fair, it was meant to be in a browser anyway.

**Comment by Th3SnowyOwl** [comment]
yes, hey I posed a more [in depth look](https://stackoverflow.com/questions/67178932/what-could-cause-website-content-to-work-when-hosted-online-but-not-when-locally) at what i think it is that's stopping it from loading, how did you make this?
