### ISSUE TITLE
I have some questions

### ISSUE THREAD

**Issue by Th3SnowyOwl** [28klotlucas2/Funkin-Html5#2]
I was wondering how you made or compiled this. (would you be interested in working on something with me? hmu)

**Comment by 28klotlucas2** [comment]
I used a secret code on the itch.io page to download it.
And I could work with you if you want.

**Comment by Th3SnowyOwl** [comment]
email nstock6696@gmail.com and ill send you an idea

**Comment by 28klotlucas2** [comment]
OK, my email is [28klotlucas@gmail.com](url)
